# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quant_client_sys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quant_client_sys.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16quant_client_sys.proto\"\xb2\x02\n\x0e\x43lientReqOrder\x12\x12\n\ninstrument\x18\x01 \x02(\t\x12\x11\n\tdirection\x18\x02 \x02(\t\x12\x11\n\tsinterval\x18\x03 \x02(\x05\x12\x0e\n\x06volume\x18\x04 \x02(\x05\x12\r\n\x05price\x18\x05 \x02(\t\x12\x10\n\x08\x61lgotype\x18\x06 \x02(\t\x12\x0e\n\x06offset\x18\x07 \x02(\t\x12\x14\n\x0cstrategyname\x18\x08 \x02(\t\x12\x0c\n\x04size\x18\t \x02(\x05\x12\x0e\n\x06wttime\x18\n \x02(\x05\x12\x10\n\x08signalid\x18\x0b \x02(\t\x12\x11\n\tpricetype\x18\x0c \x02(\t\x12\x10\n\x08\x63lientid\x18\r \x02(\t\x12\x12\n\norderstyle\x18\x0e \x02(\t\x12\x14\n\x0cmaxcancelnum\x18\x0f \x02(\x05\x12\x10\n\x08sendtime\x18\x10 \x01(\t\",\n\tOrderList\x12\x1f\n\x06orders\x18\x02 \x03(\x0b\x32\x0f.ClientReqOrder')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CLIENTREQORDER = _descriptor.Descriptor(
  name='ClientReqOrder',
  full_name='ClientReqOrder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument', full_name='ClientReqOrder.instrument', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ClientReqOrder.direction', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sinterval', full_name='ClientReqOrder.sinterval', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='ClientReqOrder.volume', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='ClientReqOrder.price', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='algotype', full_name='ClientReqOrder.algotype', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ClientReqOrder.offset', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strategyname', full_name='ClientReqOrder.strategyname', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='ClientReqOrder.size', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wttime', full_name='ClientReqOrder.wttime', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signalid', full_name='ClientReqOrder.signalid', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pricetype', full_name='ClientReqOrder.pricetype', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clientid', full_name='ClientReqOrder.clientid', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orderstyle', full_name='ClientReqOrder.orderstyle', index=13,
      number=14, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxcancelnum', full_name='ClientReqOrder.maxcancelnum', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sendtime', full_name='ClientReqOrder.sendtime', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=333,
)


_ORDERLIST = _descriptor.Descriptor(
  name='OrderList',
  full_name='OrderList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='OrderList.orders', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=379,
)

_ORDERLIST.fields_by_name['orders'].message_type = _CLIENTREQORDER
DESCRIPTOR.message_types_by_name['ClientReqOrder'] = _CLIENTREQORDER
DESCRIPTOR.message_types_by_name['OrderList'] = _ORDERLIST

ClientReqOrder = _reflection.GeneratedProtocolMessageType('ClientReqOrder', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQORDER,
  __module__ = 'quant_client_sys_pb2'
  # @@protoc_insertion_point(class_scope:ClientReqOrder)
  ))
_sym_db.RegisterMessage(ClientReqOrder)

OrderList = _reflection.GeneratedProtocolMessageType('OrderList', (_message.Message,), dict(
  DESCRIPTOR = _ORDERLIST,
  __module__ = 'quant_client_sys_pb2'
  # @@protoc_insertion_point(class_scope:OrderList)
  ))
_sym_db.RegisterMessage(OrderList)


# @@protoc_insertion_point(module_scope)
